# Railway Frontend Service (Vite/React)
[build]
command = "npm install && npm run build"
builder = "NIXPACKS"

[static]
publicDir = "dist"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
directory = "dist"